services:
  mysql:
    image: 'mysql:8.4'
    container_name: cutiaw-mysql
    environment:
      MYSQL_DATABASE: cutiaw_db
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
      MYSQL_ROOT_PASSWORD: r00t53cret
    command: --mysql-native-password=ON
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
